/*
   ▄████  ▄▄▄      ███▄ ▄███▓ ▓█████     ▄▄▄      ██▓███    ██
▒ ██▒ ▀█▒▒████▄   ▓██▒▀█▀ ██▒ ▓█   ▀    ▒████▄   ▓██░  ██ ▒▓██
░▒██░▄▄▄░▒██  ▀█▄ ▓██    ▓██░ ▒███      ▒██  ▀█▄ ▓██░ ██▓▒░▒██
░░▓█  ██▓░██▄▄▄▄██▒██    ▒██  ▒▓█  ▄    ░██▄▄▄▄██▒██▄█▓▒ ▒ ░██
░▒▓███▀▒░▒▓█   ▓██▒██▒   ░██▒▒░▒████     ▓█   ▓██▒██▒ ░  ░ ░██
 ░▒   ▒  ░▒▒   ▓▒█░ ▒░   ░  ░░░░ ▒░      ▒▒   ▓▒█▒▓▒░ ░  ░ ░▓ 
  ░   ░  ░ ░   ▒▒ ░  ░      ░░ ░ ░        ░   ▒▒ ░▒ ░       ▒ 
░ ░   ░ ░  ░   ▒  ░      ░       ░        ░   ▒  ░░         ▒ 
      ░        ░         ░   ░   ░            ░             ░ 

                               Version 1.0.1
                  Discord: https://discord.gg/EdznDm8dDk
*/

var RAW = [
    ["Five Nights at Freddy's", "Game", "Survive the night shift at Freddy Fazbear's Pizza while avoiding animatronics.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's/Images/Five-Nights-of-Freddy's.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's/Five%20Nights%20at%20Freddy's.html"],
    ["Minecraft", "Game", "Explore infinite blocky worlds, build structures, and survive monsters.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Minecraft/Images/181.png", "https://stash-files.b-cdn.net/APPS/App%20Store/APPS/Minecraft/EaglercraftX%201.8_.html"],
    ["Basket Random", "Game", "Fast-paced physics basketball with randomized players, courts, and balls.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BasketRandom/Images/66.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BasketRandom/Images/Basket%20Random.html"],
    ["Bloxorz", "Game", "Classic 3D puzzle game. Roll the block into the square hole.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BloxorZ/Images/169.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BloxorZ/Bloxorz.html"],
    ["Gobble", "Game", "Play as a hungry monster and swallow everything in sight.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Gobble/Images/37.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Gobble/Gobble.html"],
    ["OvO", "Game", "High-speed stickman platformer with wall bounces, slides, and precision jumps.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/OvO/Images/1.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/OvO/OvO.html"],
    ["Amaze", "Game", "Roll the ball and paint every square to clear each maze puzzle.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Amaze/amaze.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Amaze/amaze.html"],
    ["Friday Night Funkin'", "Game", "Hit notes in time with the music and out-rap every challenger.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Friday%20Night%20Funkin/unnamed.webp", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Friday%20Night%20Funkin/friday_night_funkin.html"],
    ["Capybara Clicker", "Game", "Click your way to capybara glory with exciting upgrades.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Capybarra%20Clicker/Capybarra%20Clicker.webp", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Capybarra%20Clicker/capybara_clicker.html"],
    ["Minecraft 1.16.5", "Game", "Build, craft, and survive in the classic block sandbox.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Minecraft%201.16.5/Minecraft%201.16.5.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Minecraft%201.16.5/Eaglercraft%201.16.5%20(u2-beta)%20(1).html"],
    ["Chess Classic", "Game", "Play chess against the computer or a friend, with hints and difficulty levels.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Classic%20Chess/Chess%20Classic.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Classic%20Chess/Chess%20Classic.html"],
    ["Five Nights at Freddy's 2", "Game", "Monitor cameras and survive the new cast of animatronics.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's%202/Five%20Nights%20of%20Freddy's%202.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's%202/Five%20Nights%20at%20Freddy's%202.html"],
    ["Rocket League", "Game", "High-flying car soccer with boosts, flips, and aerial goals.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Rocket%20league/Rocket_League_coverart.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Rocket%20league/Rocket%20League.html"],
    ["Slime Rancher", "Game", "Run a ranch full of adorable bouncy slimes.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slime%20Rancher/591.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slime%20Rancher/Slime_Rancher.html"],
    ["Slope", "Game", "Ride a ball down an endless neon slope as the speed keeps climbing.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slope/198.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slope/Slope.html"],
    ["OvO 3 Dimensions", "Game", "Stickman precision parkour expanded into full 3D environments.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/OvO%203%20Dimensions/3.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/OvO%203%20Dimensions/OvO%203%20Dimensions.html"],
    ["Five Nights at Freddy's 3", "Game", "Survive five nights monitoring cameras inside Fazbear's Fright.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's%203/40.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's%203/Five%20Nights%20at%20Freddy's%203.html"],
    ["Burrito Bison: Launcha Libre", "Game", "Launch Burrito Bison through gummy bears with wild power-ups.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Burrito%20Bison_%20Launcha%20Libre/78.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Burrito%20Bison_%20Launcha%20Libre/Burrito%20Bison_%20Launcha%20Libre.html"],
    ["Survival Race", "Game", "Outrun hazards and rival drivers in an explosive racing gauntlet.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Survival%20Race/122.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Survival%20Race/Survival%20Race.html"],
    ["Monster Tracks", "Game", "Drive monster trucks over treacherous terrain without flipping.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Monster%20Tracks/36.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Monster%20Tracks/Monster%20Tracks.html"],
    ["Geometry Dash Lite (REMAKE)", "Game", "Rhythm-based platforming rebuilt for the web. Jump, fly, and flip through danger.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Geometry%20Dash%20Lite%20(REMAKE)/27.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Geometry%20Dash%20Lite%20(REMAKE)/Geometry%20Dash%20Lite%20(REMAKE).html"],
    ["Elastic Man", "Game", "Stretchy 3D physics sandbox with real-time facial physics.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Elastic%20Man/197.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Elastic%20Man/Elastic%20Man.html"],
    ["Five Nights at Freddy's: Ultimate Custom Night", "Game", "Pick from 50 animatronics and set the difficulty from 0 to 20.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's_%20Ultimate%20Custom%20Night/192.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's_%20Ultimate%20Custom%20Night/Five%20Nights%20at%20Freddy's_%20Ultimate%20Custom%20Night.html"],
    ["Gunspin", "Game", "Time your shots and use recoil to send your firearm flying.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Gun%20Spin/91.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Gun%20Spin/Gunspin.html"],
    ["Tiny Fishing", "Game", "Cast your line, catch fish, and upgrade your rod to reach the depths.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Tiny%20Fishing/108.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Tiny%20Fishing/Tiny%20Fishing.html"],
    ["Granny", "Game", "Escape Granny's house quietly. She hears everything.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Granny/90.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Granny/Granny.html"],
    ["Granny 2", "Game", "Escape the creepy house of Granny and Grandpa without making a sound.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Granny%202/125.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Granny%202/Granny%202.html"],
    ["Retro Bowl", "Game", "Retro 8-bit football with roster management and gridiron action.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Retro%20Bowl/33.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Retro%20Bowl/Retro%20Bowl.html"],
    ["Toss The Turtle", "Game", "Launch a turtle as far as possible with cannons, rockets, and gadgets.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Toss%20The%20Turtle/110.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Toss%20The%20Turtle/Toss%20The%20Turtle.html"],
    ["Crossy Road", "Game", "Dodge traffic, hop across logs, and collect coins in this endless hopper.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Crossy%20Road/24.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Crossy%20Road/Crossy%20Road.html"],
    ["Snowball.io", "Game", "Roll giant snowballs and knock rivals off the floating ice arena.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Snow%20Ball/Snowball.io.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Snow%20Ball/snowball.html"],
    ["Football Legends", "Game", "Pull off special shots in fast 1v1 and 2v2 soccer matches.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Football%20Legends/football-legends.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Football%20Legends/football_legends.html"],
    ["Five Nights at Freddy's 4", "Game", "Defend your bedroom from the Nightmares using only a flashlight.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's%204/41.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Freddy's%204/Five%20Nights%20at%20Freddy's%204.html"],
    ["Five Nights at Winston's", "Game", "Survive night shifts evading Winston and his unsettling animatronics.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Winston's/Five%20Nights%20at%20Winston's.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Winston's/Five%20Nights%20at%20Winston's.html"],
    ["Bad Parenting", "Game", "Psychological horror. Solve disturbing puzzles and unravel the mystery of Mr. Red.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BadParenting/BadParenting.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BadParenting/BadParenting.html"],
    ["Baldi's Basics", "Game", "Collect all 7 notebooks and escape before Baldi catches you.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Baldi's%20Basics/Baldi's%20Basics__.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Baldi's%20Basics/Baldi's%20Basics.html"],
    ["PolyTrack", "Game", "Low-poly arcade racing with challenging tracks and a level builder.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/PolyTrack/PolyTrack.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/PolyTrack/PolyTrack.html"],
    ["Backrooms", "Game", "Wander endless yellow hallways. Manage stamina and avoid what lurks.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BackRooms/BackRooms.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/BackRooms/BackRooms.html"],
    ["Flappy Dunk", "Game", "Tap to guide a winged basketball through series of hoops.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Flappy%20Dunk/Flappy%20Dunk.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Flappy%20Dunk/Flappy%20Dunk.html"],
    ["Sonic.EXE 2", "Game", "The dark follow-up to the creepypasta platformer. Outrun the demonic hedgehog.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Sonic.EXE%202/Sonic.EXE%202.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Sonic.EXE%202/Sonic.EXE%202.html"],
    ["Sonic.EXE", "Game", "The original creepypasta platformer. Survive distorted levels as Tails, Knuckles, and Eggman.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Sonic.EXE/Sonic.EXE.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Sonic.EXE/Sonic.EXE.html"],
    ["Slender: The 8 Pages", "Game", "Collect all eight pages before the Slenderman finds you.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slender_%20The%208%20Pages/Slender_%20The%208%20Pages.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slender_%20The%208%20Pages/Slender_%20The%208%20Pages.html"],
    ["Geometry Dash", "Game", "Jump and fly through rhythm-based obstacle courses set to music.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Geometry%20Dash/Geometry%20Dash.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Geometry%20Dash/Geometry%20Dash.html"],
    ["Snow Rider 3D", "Game", "Sled endless snowy slopes while dodging obstacles and collecting gifts.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/SnowRider3D/SnowRider3D.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/SnowRider3D/SnowRider3D.html"],
    ["Core Ball", "Game", "Pin all your dots into the spinning core without any collisions.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/CoreBall/Coreball.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/CoreBall/CoreBall.html"],
    ["Five Nights at Last Breath", "Game", "An intense FNAF fan project that pushes your reaction speed to the limit.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Last%20Breath/Five%20Nights%20at%20Last%20Breath.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Last%20Breath/Five%20Nights%20at%20Last%20Breath.html"],
    ["Five Night's at Shrek's Hotel", "Game", "Take a cheap room at Shrek's Hotel and survive five nights of strange tasks.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Night's%20at%20Shrek's%20Hotel/Five%20Night's%20at%20Shrek's%20Hotel.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Night's%20at%20Shrek's%20Hotel/Five%20Night's%20at%20Shrek's%20Hotel.html"],
    ["Five Night's at Epstein's", "Game", "A FNAF fan parody mixing security survival with surreal horror.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/FNAF_Epstein's/FNAF_Epstein's.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/FNAF_Epstein's/FNAF_Epstein's.html"],
    ["FNAF 4", "Game", "Survive the night with a flashlight against the Nightmare animatronics.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/FNAF_4/FNAF_4.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/FNAF_4/FNAF_4.html"],
    ["Trivia Crack", "Game", "Challenge friends and players worldwide across six trivia categories.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Trivia%20Crack/Trivia%20Crack.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Trivia%20Crack/Trivia%20Crack.html"],
    ["BitLife", "Game", "Make choices from birth to death in this text life simulator.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bitlife/Bitlife.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bitlife/Bitlife.html"],
    ["Papery Planes", "Game", "Fly delicate paper planes through colorful obstacle-filled skies.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Papery%20Planes/Papery%20Planes__.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Papery%20Planes/Papery%20Planes.html"],
    ["Slow Roads", "Game", "Cruise endlessly through scenic landscapes with lo-fi music. No timers, no pressure.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slowroads/SnowRode.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Slowroads/Slowroads.html"],
    ["Bank Robbery 2", "Game", "Plan tactical heists, drill into vaults, and escape with maximum loot.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bank%20Robbery%202/Bank%20Robbery.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bank%20Robbery%202/Bank%20Robbery%202.html"],
    ["A Small World Cup", "Game", "Hilarious ragdoll soccer. Slam your player to score outrageous goals.", "https://ixla9-cdn.b-cdn.net/Apps/A%20small%20world%20cup/A%20Small%20World%20Cup.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/A%20small%20world%20cup/A%20small%20world%20cup.html"],
    ["Ragdoll Archers", "Game", "Master arrow physics and tear through waves of enemy archers.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Ragdoll%20Archers/Ragdoll%20Archers.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Ragdoll%20Archers/Ragdoll%20Archers.html"],
    ["Ragdoll Hit", "Game", "Chaotic physics combat. Punch, kick, and slam stickman opponents.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Ragdoll%20Hit/Ragdoll%20Hit.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Ragdoll%20Hit/Ragdoll%20Hit.html"],
    ["Death Run 3D", "Game", "Sprint through neon 3D tunnels where instant reactions are everything.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Death%20Run%203D/Death%20Run%203d.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Death%20Run%203D/Death%20Run%203D.html"],
    ["R.E.P.O", "Game", "Scavenge loot from hazardous facilities and dodge lethal security.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/R.E.P.O/R.E.P.O.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/R.E.P.O/R.E.P.O.html"],
    ["Drift Boss", "Game", "One-button drifting. Keep your car on the winding road without falling.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Drift%20Boss/Drift%20Boss.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Drift%20Boss/Drift%20Boss.html"],
    ["Pou", "Game", "Adopt and nurture your own alien pet with mini-games and outfits.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Pou/Pou.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Pou/Pou.html"],
    ["RERUN", "Game", "High-speed 3D platformer where momentum is everything.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/RERUN/RERUN.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/RERUN/RERUN.html"],
    ["VEX", "Game", "Stickman action platformer with lethal spikes and precision courses.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/VEX/VEX.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/VEX/VEX.html"],
    ["Temple Run 2", "Game", "Escape with the cursed idol while demon monkeys chase you down.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Temple%20Run%202/Temple%20Run%202.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Temple%20Run%202/Temple%20Run%202.html"],
    ["SCP: Containment Breach", "Game", "Survive a facility breach and avoid anomalous entities like SCP-173.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/SCP_%20Containment%20Breach/SCP_%20Containment%20Breach.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/SCP_%20Containment%20Breach/SCP_%20Containment%20Breach.html"],
    ["Cookie Clicker", "Game", "Bake trillions of cookies and unlock hundreds of upgrades.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Cookie%20Clicker/Cookie%20Clicker.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Cookie%20Clicker/Cookie%20Clicker.html"],
    ["Bendy and the Ink Machine: Full Set", "Game", "The complete horror mystery of Joey Drew Studios across all chapters.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bendy%20and%20the%20Ink%20Machine%20%5Bfull%20set%5D/Bendy%20and%20the%20Ink%20Machine%20%5Bfull%20set%5D.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bendy%20and%20the%20Ink%20Machine%20%5Bfull%20set%5D/Bendy%20and%20the%20Ink%20Machine%20%5Bfull%20set%5D.html"],
    ["Bendy and the Ink Machine", "Game", "Vintage animation studio turned nightmare puzzle-horror.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bendy%20and%20the%20Ink%20Machine/Bendy%20and%20the%20Ink%20Machine.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Bendy%20and%20the%20Ink%20Machine/Bendy%20and%20the%20Ink%20Machine.html"],
    ["Achievement Unlocked", "Game", "Unlock all 99 achievements in one chaotic room.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Achievement%20Unlocked/Achievement%20Unlocked.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Achievement%20Unlocked/Achievement%20Unlocked.html"],
    ["Wordle", "Game", "Guess the secret 5-letter word in 6 tries.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Wordle/Wordle.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Wordle/Wordle.html"],
    ["Cluster Truck", "Game", "Leap across a highway of speeding, crashing trucks.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Cluster%20Truck/Cluster%20Truck.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Cluster%20Truck/Cluster%20truck.html"],
    ["Indian Truck Simulator", "Game", "Drive heavy cargo trucks across winding mountain passes and busy streets.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Indian%20Truck%20Simulator/Indian%20Truck%20Simulator.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Indian%20Truck%20Simulator/Indian%20Truck%20Simulator.html"],
    ["Infinite Craft", "Game", "Combine the four elements to discover thousands of unique items.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Infinite%20Craft/Infinite%20Craft.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Infinite%20Craft/Infinite%20Craft.html"],
    ["Ice Fishing", "Game", "Drill through frozen lakes and reel in record catches.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Ice%20Fishing/Ice%20Fishing.webp", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Ice%20Fishing/Ice%20Fishing.html"],
    ["Haunted School", "Game", "Solve puzzles and banish vengeful spirits before it is too late.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Haunted%20School/Haunted%20School.jpeg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Haunted%20School/Haunted%20School.html"],
    ["Five Nights at Candy's 2", "Game", "Lure animatronics away and survive five nightmarish shifts.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Candy%E2%80%99s%202/Five%20Nights%20at%20Candy%E2%80%99s%202.webp", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Candy%E2%80%99s%202/Five%20Nights%20at%20Candy%E2%80%99s%202.html"],
    ["Five Nights at Candy's", "Game", "Night watch at Candy's Burgers and Fries. Watch the cameras.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Candy%E2%80%99s%201/Five%20Nights%20at%20Candy%E2%80%99s%201.webp", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Five%20Nights%20at%20Candy%E2%80%99s%201/Five%20Nights%20at%20Candy%E2%80%99s%201.html"],
    ["Idle Dice", "Game", "Roll dice, stack multipliers, and prestige for huge scores.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Idle%20Dice/Idle%20Dice.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Idle%20Dice/Idle%20Dice.html"],
    ["Noob Miner", "Game", "Mine ores, trade, and upgrade to help Noob escape prison.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Noob%20Miner/Noob%20Miner.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Noob%20Miner/Noob%20Miner.html"],
    ["ChatGPT", "ai", "Powerful AI assistant for questions, ideas, and code help.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/ChatGPT/chatgpt-1.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/ChatGPT/chatgpt.html"],
    ["Minecraft 26.2", "Game", "Build, craft, and survive in the newest Minecraft version.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Minecraft%2026.2/minecraft.jpg", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Minecraft%2026.2/26.2.html"],
    ["A Bite at Freddy's", "Game", "Fan-made FNAF horror with cameras, lights, and power management.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/A%20Bite%20at%20Freddy's/A%20Bite%20at%20Freddy's.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/A%20Bite%20at%20Freddy's/A%20Bite%20at%20Freddy's.html"],
    ["Throw a Potato", "Game", "Fling a potato as far as you possibly can.", "https://ixla9-cdn.b-cdn.net/Apps/Throw%20a%20potato/Trow%20a%20Potato.png", "https://ixla9-cdn.b-cdn.net/Apps/Throw%20a%20potato/Throw%20a%20Potato.html"],
    ["Super Liquid Soccer", "Game", "Fast-paced soccer with floppy ragdoll players and wild shots.", "https://ixla9-cdn.b-cdn.net/Apps/Super%20liquid%20soccer/Super%20Liquid%20Soccer.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Super%20liquid%20soccer/Super%20Liquid%20Soccer.html"],
    ["Soundboard", "App", "A big soundboard full of sounds to play anytime.", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Soundboard/Soundboard.png", "https://Stash-Files.b-cdn.net/APPS/App%20Store/APPS/Soundboard/Soundboard.html"],
    ["Brotato", "Game", "Survive alien waves as a potato armed with up to six weapons at once.", "https://ixla9-cdn.b-cdn.net/Apps/Brotato/Brotato.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Brotato/Brotato.html"],
    ["Boxing Random", "Game", "Goofy physics boxing with random fighters and wild one-punch KOs.", "https://ixla9-cdn.b-cdn.net/Apps/Boxing%20Random/Boxing%20Random.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Boxing%20Random/Boxing%20Random.html"],
    ["Boba Simulator", "Game", "Mix and serve boba drinks in your own cozy little shop.", "https://ixla9-cdn.b-cdn.net/Apps/Boba%20Simulator/Boxing%20Random.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Boba%20Simulator/Boxing%20Random.html"],
    ["Bounce Back", "Game", "Keep the ball bouncing and clear every tricky level.", "https://ixla9-cdn.b-cdn.net/Apps/Bounce%20Back/Bounce%20Back.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Bounce%20Back/Bounce%20Back.html"],
    ["Bottle Cracks", "Game", "Slice and crack bottles in satisfying puzzle chains.", "https://ixla9-cdn.b-cdn.net/Apps/Bottle%20Cracks/Bottle%20Cracks.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Bottle%20Cracks/Bottle%20Cracks.html"],
    ["Blood Tournament", "Game", "Brutal ragdoll fighting with waves of enemies and big weapons.", "https://ixla9-cdn.b-cdn.net/Apps/Blood%20Tournament/Blood%20Tournament.png", "https://ixla9-cdn.b-cdn.net/Apps/Blood%20Tournament/Blood%20Tournament.html"],
    ["Big Shot Boxing", "Game", "Dodge, jab, and knockout your way to the championship belt.", "https://ixla9-cdn.b-cdn.net/Apps/Big%20Shot%20Boxing/Big%20Shot%20Boxing.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Big%20Shot%20Boxing/Big%20Shot%20Boxing.html"],
    ["Block Blast", "Game", "Place colorful blocks and clear lines in this puzzle classic.", "https://ixla9-cdn.b-cdn.net/Apps/Block%20Blast/Block%20Blast.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Block%20Blast/Block%20Blast.html"],
    ["Arthur's Nightmare", "Game", "Survive creepy nights in this Arthur fan-made horror game.", "https://ixla9-cdn.b-cdn.net/Apps/Arthur%E2%80%99s%20Nightmare/Arthur%E2%80%99s%20Nightmare.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Arthur%E2%80%99s%20Nightmare/Arthur%E2%80%99s%20Nightmare.html"],
    ["Angry Birds", "Game", "Slingshot birds at greedy pigs and topple their forts.", "https://ixla9-cdn.b-cdn.net/Apps/Angry%20Birds/Angry%20Birds.jpg", "https://ixla9-cdn.b-cdn.net/Apps/Angry%20Birds/Angry%20Birds.html"],
    ["Adventure Capitalist", "Game", "Grow a business empire from one lemonade stand to the stars.", "https://ixla9-cdn.b-cdn.net/Apps/Adventure%20Capitalist/Adventure%20Capitalist.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/Adventure%20Capitalist/Adventure%20Capitalist.html"],
    ["A Dark Room", "Game", "A minimalist text adventure that slowly unfolds its mystery.", "https://ixla9-cdn.b-cdn.net/Apps/A%20Dark%20Room/A%20Dark%20Room.png", "https://ixla9-cdn.b-cdn.net/Apps/A%20Dark%20Room/A%20Dark%20Room.html"],
    ["A Dance of Fire and Ice", "Game", "Guide two orbiting dots through twisting rhythm paths.", "https://ixla9-cdn.b-cdn.net/Apps/A%20Dance%20of%20Fire%20and%20Ice/A%20Dance%20of%20Fire%20and%20Ice.jpeg", "https://ixla9-cdn.b-cdn.net/Apps/A%20Dance%20of%20Fire%20and%20Ice/A%20Dance%20of%20Fire%20and%20Ice.html"]
];

var STASH_GAMES = [];
for (var i = 0; i < RAW.length; i++) {
    var e = RAW[i];
    STASH_GAMES.push({ id: i + 1, name: e[0], cat: e[1], desc: e[2], img: e[3], url: e[4] });
}

window.STASH_GAMES = STASH_GAMES;

window.StashAPI = {
    all: function () { return STASH_GAMES.slice(); },
    games: function () { return STASH_GAMES.filter(function (g) { return (g.cat || 'Game') === 'Game'; }); },
    apps: function () { return STASH_GAMES.filter(function (g) { return (g.cat || 'Game') !== 'Game'; }); },
    find: function (q) {
        var n = String(q || '').toLowerCase().replace(/[^a-z0-9]/g, '');
        var r = [];
        for (var k = 0; k < STASH_GAMES.length; k++) {
            var nn = STASH_GAMES[k].name.toLowerCase().replace(/[^a-z0-9]/g, '');
            if (nn === n) return STASH_GAMES[k];
            if (nn.indexOf(n) > -1) r.push(STASH_GAMES[k]);
        }
        return r.length === 1 ? r[0] : r;
    }
};
